// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox (
    aggregate_type, aggregate_id, event_type, payload
) VALUES (
    $1, $2, $3, $4
) RETURNING id, aggregate_type, aggregate_id, event_type, payload, published, created_at, published_at
`

type CreateOutboxEventParams struct {
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Published,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const deleteOldPublishedEvents = `-- name: DeleteOldPublishedEvents :exec
DELETE FROM outbox
WHERE published = true AND published_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) DeleteOldPublishedEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldPublishedEvents)
	return err
}

const getUnpublishedEvents = `-- name: GetUnpublishedEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, published, created_at, published_at FROM outbox
WHERE published = false
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetUnpublishedEvents(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getUnpublishedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Published,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventPublished = `-- name: MarkEventPublished :exec
UPDATE outbox
SET published = true, published_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventPublished, id)
	return err
}
