// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountNotesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountSources(ctx context.Context) (int64, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	DeleteNote(ctx context.Context, id uuid.UUID) error
	DeleteOldPublishedEvents(ctx context.Context) error
	DeleteSource(ctx context.Context, id uuid.UUID) error
	GetNote(ctx context.Context, id uuid.UUID) (Note, error)
	GetSource(ctx context.Context, id uuid.UUID) (Source, error)
	GetUnpublishedEvents(ctx context.Context, limit int32) ([]Outbox, error)
	ListNotesBySource(ctx context.Context, arg ListNotesBySourceParams) ([]Note, error)
	ListNotesByUser(ctx context.Context, arg ListNotesByUserParams) ([]Note, error)
	ListPublicNotes(ctx context.Context, arg ListPublicNotesParams) ([]Note, error)
	ListSources(ctx context.Context, arg ListSourcesParams) ([]Source, error)
	ListSourcesByType(ctx context.Context, arg ListSourcesByTypeParams) ([]Source, error)
	MarkEventPublished(ctx context.Context, id uuid.UUID) error
	SearchSourcesByTitle(ctx context.Context, arg SearchSourcesByTitleParams) ([]Source, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error)
}

var _ Querier = (*Queries)(nil)
