// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (id, user_id, name, description, is_public, source_ids)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, description, is_public, source_ids, created_at, updated_at
`

type CreateCollectionParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	IsPublic    pgtype.Bool `db:"is_public" json:"is_public"`
	SourceIds   []byte      `db:"source_ids" json:"source_ids"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.SourceIds,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.SourceIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, user_id, name, description, is_public, source_ids, created_at, updated_at
FROM collections
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id pgtype.UUID) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.SourceIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollectionsByUser = `-- name: ListCollectionsByUser :many
SELECT id, user_id, name, description, is_public, source_ids, created_at, updated_at
FROM collections
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCollectionsByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListCollectionsByUser(ctx context.Context, arg ListCollectionsByUserParams) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollectionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.SourceIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCollectionsByUser = `-- name: ListPublicCollectionsByUser :many
SELECT id, user_id, name, description, is_public, source_ids, created_at, updated_at
FROM collections
WHERE user_id = $1 AND is_public = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicCollectionsByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicCollectionsByUser(ctx context.Context, arg ListPublicCollectionsByUserParams) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listPublicCollectionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.SourceIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourceExists = `-- name: SourceExists :one
SELECT EXISTS (SELECT 1 FROM sources WHERE id = $1)
`

func (q *Queries) SourceExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, sourceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET name = $2, description = $3, is_public = $4, source_ids = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, description, is_public, source_ids, created_at, updated_at
`

type UpdateCollectionParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	IsPublic    pgtype.Bool `db:"is_public" json:"is_public"`
	SourceIds   []byte      `db:"source_ids" json:"source_ids"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.SourceIds,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.SourceIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
