// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: library.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLibraryItem = `-- name: CreateLibraryItem :one
INSERT INTO user_library_items (id, user_id, source_id, status, progress_value, progress_unit, visibility, started_at, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, source_id, status, progress_value, progress_unit, visibility, started_at, completed_at, created_at, updated_at
`

type CreateLibraryItemParams struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	SourceID      pgtype.UUID        `db:"source_id" json:"source_id"`
	Status        string             `db:"status" json:"status"`
	ProgressValue pgtype.Int4        `db:"progress_value" json:"progress_value"`
	ProgressUnit  pgtype.Text        `db:"progress_unit" json:"progress_unit"`
	Visibility    string             `db:"visibility" json:"visibility"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) CreateLibraryItem(ctx context.Context, arg CreateLibraryItemParams) (UserLibraryItem, error) {
	row := q.db.QueryRow(ctx, createLibraryItem,
		arg.ID,
		arg.UserID,
		arg.SourceID,
		arg.Status,
		arg.ProgressValue,
		arg.ProgressUnit,
		arg.Visibility,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i UserLibraryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Status,
		&i.ProgressValue,
		&i.ProgressUnit,
		&i.Visibility,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLibraryItem = `-- name: DeleteLibraryItem :exec
DELETE FROM user_library_items WHERE id = $1
`

func (q *Queries) DeleteLibraryItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLibraryItem, id)
	return err
}

const getLibraryItemByID = `-- name: GetLibraryItemByID :one
SELECT id, user_id, source_id, status, progress_value, progress_unit, visibility, started_at, completed_at, created_at, updated_at
FROM user_library_items
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLibraryItemByID(ctx context.Context, id pgtype.UUID) (UserLibraryItem, error) {
	row := q.db.QueryRow(ctx, getLibraryItemByID, id)
	var i UserLibraryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Status,
		&i.ProgressValue,
		&i.ProgressUnit,
		&i.Visibility,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLibraryItemsByUser = `-- name: ListLibraryItemsByUser :many
SELECT id, user_id, source_id, status, progress_value, progress_unit, visibility, started_at, completed_at, created_at, updated_at
FROM user_library_items
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLibraryItemsByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListLibraryItemsByUser(ctx context.Context, arg ListLibraryItemsByUserParams) ([]UserLibraryItem, error) {
	rows, err := q.db.Query(ctx, listLibraryItemsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserLibraryItem{}
	for rows.Next() {
		var i UserLibraryItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Status,
			&i.ProgressValue,
			&i.ProgressUnit,
			&i.Visibility,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryItemsByUserWithSources = `-- name: ListLibraryItemsByUserWithSources :many
SELECT uli.id, uli.user_id, uli.source_id, uli.status, uli.progress_value, uli.progress_unit, uli.visibility, uli.started_at, uli.completed_at, uli.created_at, uli.updated_at,
       s.title, s.subtitle, s.type, s.publisher, s.isbn
FROM user_library_items uli
JOIN sources s ON s.id = uli.source_id
WHERE uli.user_id = $1
ORDER BY uli.created_at DESC
LIMIT $2 OFFSET $3
`

type ListLibraryItemsByUserWithSourcesParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type ListLibraryItemsByUserWithSourcesRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	SourceID      pgtype.UUID        `db:"source_id" json:"source_id"`
	Status        string             `db:"status" json:"status"`
	ProgressValue pgtype.Int4        `db:"progress_value" json:"progress_value"`
	ProgressUnit  pgtype.Text        `db:"progress_unit" json:"progress_unit"`
	Visibility    string             `db:"visibility" json:"visibility"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Title         string             `db:"title" json:"title"`
	Subtitle      pgtype.Text        `db:"subtitle" json:"subtitle"`
	Type          string             `db:"type" json:"type"`
	Publisher     pgtype.Text        `db:"publisher" json:"publisher"`
	Isbn          pgtype.Text        `db:"isbn" json:"isbn"`
}

func (q *Queries) ListLibraryItemsByUserWithSources(ctx context.Context, arg ListLibraryItemsByUserWithSourcesParams) ([]ListLibraryItemsByUserWithSourcesRow, error) {
	rows, err := q.db.Query(ctx, listLibraryItemsByUserWithSources, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibraryItemsByUserWithSourcesRow{}
	for rows.Next() {
		var i ListLibraryItemsByUserWithSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Status,
			&i.ProgressValue,
			&i.ProgressUnit,
			&i.Visibility,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Subtitle,
			&i.Type,
			&i.Publisher,
			&i.Isbn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicLibraryItemsByUser = `-- name: ListPublicLibraryItemsByUser :many
SELECT id, user_id, source_id, status, progress_value, progress_unit, visibility, started_at, completed_at, created_at, updated_at
FROM user_library_items
WHERE user_id = $1 AND visibility = 'public'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicLibraryItemsByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicLibraryItemsByUser(ctx context.Context, arg ListPublicLibraryItemsByUserParams) ([]UserLibraryItem, error) {
	rows, err := q.db.Query(ctx, listPublicLibraryItemsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserLibraryItem{}
	for rows.Next() {
		var i UserLibraryItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Status,
			&i.ProgressValue,
			&i.ProgressUnit,
			&i.Visibility,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicLibraryItemsByUsername = `-- name: ListPublicLibraryItemsByUsername :many
SELECT uli.id, uli.user_id, uli.source_id, uli.status, uli.progress_value, uli.progress_unit, uli.visibility, uli.started_at, uli.completed_at, uli.created_at, uli.updated_at
FROM user_library_items uli
JOIN users u ON u.id = uli.user_id
WHERE u.username = $1 AND uli.visibility = 'public'
ORDER BY uli.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicLibraryItemsByUsernameParams struct {
	Username string `db:"username" json:"username"`
	Limit    int32  `db:"limit" json:"limit"`
	Offset   int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicLibraryItemsByUsername(ctx context.Context, arg ListPublicLibraryItemsByUsernameParams) ([]UserLibraryItem, error) {
	rows, err := q.db.Query(ctx, listPublicLibraryItemsByUsername, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserLibraryItem{}
	for rows.Next() {
		var i UserLibraryItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Status,
			&i.ProgressValue,
			&i.ProgressUnit,
			&i.Visibility,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicLibraryItemsByUsernameWithSources = `-- name: ListPublicLibraryItemsByUsernameWithSources :many
SELECT uli.id, uli.user_id, uli.source_id, uli.status, uli.progress_value, uli.progress_unit, uli.visibility, uli.started_at, uli.completed_at, uli.created_at, uli.updated_at,
       s.title, s.subtitle, s.type, s.publisher, s.isbn
FROM user_library_items uli
JOIN users u ON u.id = uli.user_id
JOIN sources s ON s.id = uli.source_id
WHERE u.username = $1 AND uli.visibility = 'public'
ORDER BY uli.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicLibraryItemsByUsernameWithSourcesParams struct {
	Username string `db:"username" json:"username"`
	Limit    int32  `db:"limit" json:"limit"`
	Offset   int32  `db:"offset" json:"offset"`
}

type ListPublicLibraryItemsByUsernameWithSourcesRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	SourceID      pgtype.UUID        `db:"source_id" json:"source_id"`
	Status        string             `db:"status" json:"status"`
	ProgressValue pgtype.Int4        `db:"progress_value" json:"progress_value"`
	ProgressUnit  pgtype.Text        `db:"progress_unit" json:"progress_unit"`
	Visibility    string             `db:"visibility" json:"visibility"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Title         string             `db:"title" json:"title"`
	Subtitle      pgtype.Text        `db:"subtitle" json:"subtitle"`
	Type          string             `db:"type" json:"type"`
	Publisher     pgtype.Text        `db:"publisher" json:"publisher"`
	Isbn          pgtype.Text        `db:"isbn" json:"isbn"`
}

func (q *Queries) ListPublicLibraryItemsByUsernameWithSources(ctx context.Context, arg ListPublicLibraryItemsByUsernameWithSourcesParams) ([]ListPublicLibraryItemsByUsernameWithSourcesRow, error) {
	rows, err := q.db.Query(ctx, listPublicLibraryItemsByUsernameWithSources, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicLibraryItemsByUsernameWithSourcesRow{}
	for rows.Next() {
		var i ListPublicLibraryItemsByUsernameWithSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Status,
			&i.ProgressValue,
			&i.ProgressUnit,
			&i.Visibility,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Subtitle,
			&i.Type,
			&i.Publisher,
			&i.Isbn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibraryItem = `-- name: UpdateLibraryItem :one
UPDATE user_library_items
SET status = $2, progress_value = $3, progress_unit = $4, visibility = $5, started_at = $6, completed_at = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, source_id, status, progress_value, progress_unit, visibility, started_at, completed_at, created_at, updated_at
`

type UpdateLibraryItemParams struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Status        string             `db:"status" json:"status"`
	ProgressValue pgtype.Int4        `db:"progress_value" json:"progress_value"`
	ProgressUnit  pgtype.Text        `db:"progress_unit" json:"progress_unit"`
	Visibility    string             `db:"visibility" json:"visibility"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) UpdateLibraryItem(ctx context.Context, arg UpdateLibraryItemParams) (UserLibraryItem, error) {
	row := q.db.QueryRow(ctx, updateLibraryItem,
		arg.ID,
		arg.Status,
		arg.ProgressValue,
		arg.ProgressUnit,
		arg.Visibility,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i UserLibraryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Status,
		&i.ProgressValue,
		&i.ProgressUnit,
		&i.Visibility,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
