// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotesByUser = `-- name: CountNotesByUser :one
SELECT COUNT(*) FROM notes WHERE user_id = $1
`

func (q *Queries) CountNotesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (id, user_id, source_id, content, content_type, is_public, annotations, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at
`

type CreateNoteParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	SourceID    pgtype.UUID `db:"source_id" json:"source_id"`
	Content     string      `db:"content" json:"content"`
	ContentType string      `db:"content_type" json:"content_type"`
	IsPublic    pgtype.Bool `db:"is_public" json:"is_public"`
	Annotations []byte      `db:"annotations" json:"annotations"`
	Tags        []byte      `db:"tags" json:"tags"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.ID,
		arg.UserID,
		arg.SourceID,
		arg.Content,
		arg.ContentType,
		arg.IsPublic,
		arg.Annotations,
		arg.Tags,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Content,
		&i.ContentType,
		&i.IsPublic,
		&i.Annotations,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at
FROM notes
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetNoteByID(ctx context.Context, id pgtype.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Content,
		&i.ContentType,
		&i.IsPublic,
		&i.Annotations,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesBySource = `-- name: ListNotesBySource :many
SELECT id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at
FROM notes
WHERE source_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotesBySourceParams struct {
	SourceID pgtype.UUID `db:"source_id" json:"source_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListNotesBySource(ctx context.Context, arg ListNotesBySourceParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesBySource, arg.SourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Content,
			&i.ContentType,
			&i.IsPublic,
			&i.Annotations,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesByUser = `-- name: ListNotesByUser :many
SELECT id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at
FROM notes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotesByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListNotesByUser(ctx context.Context, arg ListNotesByUserParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Content,
			&i.ContentType,
			&i.IsPublic,
			&i.Annotations,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicNotes = `-- name: ListPublicNotes :many
SELECT id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at
FROM notes
WHERE is_public = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicNotesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicNotes(ctx context.Context, arg ListPublicNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listPublicNotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Content,
			&i.ContentType,
			&i.IsPublic,
			&i.Annotations,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicNotesBySource = `-- name: ListPublicNotesBySource :many
SELECT id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at
FROM notes
WHERE source_id = $1 AND is_public = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicNotesBySourceParams struct {
	SourceID pgtype.UUID `db:"source_id" json:"source_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicNotesBySource(ctx context.Context, arg ListPublicNotesBySourceParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listPublicNotesBySource, arg.SourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Content,
			&i.ContentType,
			&i.IsPublic,
			&i.Annotations,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicNotesByUser = `-- name: ListPublicNotesByUser :many
SELECT id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at
FROM notes
WHERE user_id = $1 AND is_public = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicNotesByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicNotesByUser(ctx context.Context, arg ListPublicNotesByUserParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listPublicNotesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Content,
			&i.ContentType,
			&i.IsPublic,
			&i.Annotations,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET source_id = $2, content = $3, content_type = $4, is_public = $5, annotations = $6, tags = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at
`

type UpdateNoteParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	SourceID    pgtype.UUID `db:"source_id" json:"source_id"`
	Content     string      `db:"content" json:"content"`
	ContentType string      `db:"content_type" json:"content_type"`
	IsPublic    pgtype.Bool `db:"is_public" json:"is_public"`
	Annotations []byte      `db:"annotations" json:"annotations"`
	Tags        []byte      `db:"tags" json:"tags"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.SourceID,
		arg.Content,
		arg.ContentType,
		arg.IsPublic,
		arg.Annotations,
		arg.Tags,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Content,
		&i.ContentType,
		&i.IsPublic,
		&i.Annotations,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
