// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, display_name, bio, public_profile, created_at, updated_at
FROM profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.PublicProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicProfileByUsername = `-- name: GetPublicProfileByUsername :one
SELECT p.id, p.user_id, u.username, p.display_name, p.bio, p.public_profile, p.created_at, p.updated_at
FROM profiles p
JOIN users u ON u.id = p.user_id
WHERE u.username = $1 AND p.public_profile = true
LIMIT 1
`

type GetPublicProfileByUsernameRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	Username      string             `db:"username" json:"username"`
	DisplayName   pgtype.Text        `db:"display_name" json:"display_name"`
	Bio           pgtype.Text        `db:"bio" json:"bio"`
	PublicProfile pgtype.Bool        `db:"public_profile" json:"public_profile"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPublicProfileByUsername(ctx context.Context, username string) (GetPublicProfileByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfileByUsername, username)
	var i GetPublicProfileByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.PublicProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
WITH upserted AS (
    INSERT INTO profiles (id, user_id, display_name, bio, public_profile)
    VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT (user_id) DO UPDATE SET
        display_name = EXCLUDED.display_name,
        bio = EXCLUDED.bio,
        public_profile = EXCLUDED.public_profile,
        updated_at = NOW()
    RETURNING id, user_id, display_name, bio, public_profile, created_at, updated_at
)
SELECT p.id, p.user_id, u.username, p.display_name, p.bio, p.public_profile, p.created_at, p.updated_at
FROM upserted p
JOIN users u ON u.id = p.user_id
`

type UpsertProfileParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
	DisplayName   pgtype.Text `db:"display_name" json:"display_name"`
	Bio           pgtype.Text `db:"bio" json:"bio"`
	PublicProfile pgtype.Bool `db:"public_profile" json:"public_profile"`
}

type UpsertProfileRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	Username      string             `db:"username" json:"username"`
	DisplayName   pgtype.Text        `db:"display_name" json:"display_name"`
	Bio           pgtype.Text        `db:"bio" json:"bio"`
	PublicProfile pgtype.Bool        `db:"public_profile" json:"public_profile"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UpsertProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.ID,
		arg.UserID,
		arg.DisplayName,
		arg.Bio,
		arg.PublicProfile,
	)
	var i UpsertProfileRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.PublicProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
