// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (id, user_id, source_id, rating, content, is_public)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, source_id, rating, content, is_public, created_at, updated_at
`

type CreateReviewParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	SourceID pgtype.UUID `db:"source_id" json:"source_id"`
	Rating   pgtype.Int4 `db:"rating" json:"rating"`
	Content  pgtype.Text `db:"content" json:"content"`
	IsPublic pgtype.Bool `db:"is_public" json:"is_public"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ID,
		arg.UserID,
		arg.SourceID,
		arg.Rating,
		arg.Content,
		arg.IsPublic,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Rating,
		&i.Content,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, user_id, source_id, rating, content, is_public, created_at, updated_at
FROM reviews
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetReviewByID(ctx context.Context, id pgtype.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Rating,
		&i.Content,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicReviewsBySource = `-- name: ListPublicReviewsBySource :many
SELECT id, user_id, source_id, rating, content, is_public, created_at, updated_at
FROM reviews
WHERE source_id = $1 AND is_public = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicReviewsBySourceParams struct {
	SourceID pgtype.UUID `db:"source_id" json:"source_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicReviewsBySource(ctx context.Context, arg ListPublicReviewsBySourceParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listPublicReviewsBySource, arg.SourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Rating,
			&i.Content,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicReviewsByUser = `-- name: ListPublicReviewsByUser :many
SELECT id, user_id, source_id, rating, content, is_public, created_at, updated_at
FROM reviews
WHERE user_id = $1 AND is_public = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicReviewsByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicReviewsByUser(ctx context.Context, arg ListPublicReviewsByUserParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listPublicReviewsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Rating,
			&i.Content,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsBySource = `-- name: ListReviewsBySource :many
SELECT id, user_id, source_id, rating, content, is_public, created_at, updated_at
FROM reviews
WHERE source_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListReviewsBySourceParams struct {
	SourceID pgtype.UUID `db:"source_id" json:"source_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListReviewsBySource(ctx context.Context, arg ListReviewsBySourceParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsBySource, arg.SourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Rating,
			&i.Content,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUser = `-- name: ListReviewsByUser :many
SELECT id, user_id, source_id, rating, content, is_public, created_at, updated_at
FROM reviews
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListReviewsByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListReviewsByUser(ctx context.Context, arg ListReviewsByUserParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Rating,
			&i.Content,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET rating = $2, content = $3, is_public = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, source_id, rating, content, is_public, created_at, updated_at
`

type UpdateReviewParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Rating   pgtype.Int4 `db:"rating" json:"rating"`
	Content  pgtype.Text `db:"content" json:"content"`
	IsPublic pgtype.Bool `db:"is_public" json:"is_public"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.ID,
		arg.Rating,
		arg.Content,
		arg.IsPublic,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Rating,
		&i.Content,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
