// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSources = `-- name: CountSources :one
SELECT COUNT(*) FROM sources
`

func (q *Queries) CountSources(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (id, title, subtitle, type, description, publisher, isbn, doi, url, external_id, tags, published_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, title, subtitle, type, description, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at
`

type CreateSourceParams struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Subtitle    pgtype.Text        `db:"subtitle" json:"subtitle"`
	Type        string             `db:"type" json:"type"`
	Description pgtype.Text        `db:"description" json:"description"`
	Publisher   pgtype.Text        `db:"publisher" json:"publisher"`
	Isbn        pgtype.Text        `db:"isbn" json:"isbn"`
	Doi         pgtype.Text        `db:"doi" json:"doi"`
	Url         pgtype.Text        `db:"url" json:"url"`
	ExternalID  pgtype.Text        `db:"external_id" json:"external_id"`
	Tags        []byte             `db:"tags" json:"tags"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.Type,
		arg.Description,
		arg.Publisher,
		arg.Isbn,
		arg.Doi,
		arg.Url,
		arg.ExternalID,
		arg.Tags,
		arg.PublishedAt,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Type,
		&i.Description,
		&i.Publisher,
		&i.Isbn,
		&i.Doi,
		&i.Url,
		&i.ExternalID,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const getBookMetadata = `-- name: GetBookMetadata :one
SELECT source_id, isbn_10, isbn_13, publisher, page_count, language, cover_url, created_at, updated_at
FROM book_metadata
WHERE source_id = $1
LIMIT 1
`

func (q *Queries) GetBookMetadata(ctx context.Context, sourceID pgtype.UUID) (BookMetadatum, error) {
	row := q.db.QueryRow(ctx, getBookMetadata, sourceID)
	var i BookMetadatum
	err := row.Scan(
		&i.SourceID,
		&i.Isbn10,
		&i.Isbn13,
		&i.Publisher,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookSourceByID = `-- name: GetBookSourceByID :one
SELECT id, title, subtitle, type, description, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at
FROM sources
WHERE id = $1 AND type = 'book'
LIMIT 1
`

func (q *Queries) GetBookSourceByID(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getBookSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Type,
		&i.Description,
		&i.Publisher,
		&i.Isbn,
		&i.Doi,
		&i.Url,
		&i.ExternalID,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, title, subtitle, type, description, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at
FROM sources
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSourceByID(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Type,
		&i.Description,
		&i.Publisher,
		&i.Isbn,
		&i.Doi,
		&i.Url,
		&i.ExternalID,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBookMetadata = `-- name: InsertBookMetadata :one
INSERT INTO book_metadata (source_id, isbn_10, isbn_13, publisher, page_count, language, cover_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING source_id, isbn_10, isbn_13, publisher, page_count, language, cover_url, created_at, updated_at
`

type InsertBookMetadataParams struct {
	SourceID  pgtype.UUID `db:"source_id" json:"source_id"`
	Isbn10    pgtype.Text `db:"isbn_10" json:"isbn_10"`
	Isbn13    pgtype.Text `db:"isbn_13" json:"isbn_13"`
	Publisher pgtype.Text `db:"publisher" json:"publisher"`
	PageCount pgtype.Int4 `db:"page_count" json:"page_count"`
	Language  pgtype.Text `db:"language" json:"language"`
	CoverUrl  pgtype.Text `db:"cover_url" json:"cover_url"`
}

func (q *Queries) InsertBookMetadata(ctx context.Context, arg InsertBookMetadataParams) (BookMetadatum, error) {
	row := q.db.QueryRow(ctx, insertBookMetadata,
		arg.SourceID,
		arg.Isbn10,
		arg.Isbn13,
		arg.Publisher,
		arg.PageCount,
		arg.Language,
		arg.CoverUrl,
	)
	var i BookMetadatum
	err := row.Scan(
		&i.SourceID,
		&i.Isbn10,
		&i.Isbn13,
		&i.Publisher,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBookSource = `-- name: InsertBookSource :one
INSERT INTO sources (id, title, subtitle, type, description, publisher, isbn, url, external_id, tags, published_at)
VALUES ($1, $2, $3, 'book', $4, $5, COALESCE($6, $7), $8, $9, $10, $11)
RETURNING id, title, subtitle, type, description, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at
`

type InsertBookSourceParams struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Subtitle    pgtype.Text        `db:"subtitle" json:"subtitle"`
	Description pgtype.Text        `db:"description" json:"description"`
	Publisher   pgtype.Text        `db:"publisher" json:"publisher"`
	Column6     interface{}        `db:"column_6" json:"column_6"`
	Column7     interface{}        `db:"column_7" json:"column_7"`
	Url         pgtype.Text        `db:"url" json:"url"`
	ExternalID  pgtype.Text        `db:"external_id" json:"external_id"`
	Tags        []byte             `db:"tags" json:"tags"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

func (q *Queries) InsertBookSource(ctx context.Context, arg InsertBookSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, insertBookSource,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Publisher,
		arg.Column6,
		arg.Column7,
		arg.Url,
		arg.ExternalID,
		arg.Tags,
		arg.PublishedAt,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Type,
		&i.Description,
		&i.Publisher,
		&i.Isbn,
		&i.Doi,
		&i.Url,
		&i.ExternalID,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSourceContributor = `-- name: InsertSourceContributor :one
INSERT INTO source_contributors (source_id, contributor_id, role, position)
VALUES ($1, $2, $3, $4)
RETURNING contributor_id, $5::text AS name, role, position, NOW()::timestamptz AS created_at, NOW()::timestamptz AS updated_at
`

type InsertSourceContributorParams struct {
	SourceID        pgtype.UUID `db:"source_id" json:"source_id"`
	ContributorID   pgtype.UUID `db:"contributor_id" json:"contributor_id"`
	Role            string      `db:"role" json:"role"`
	Position        int32       `db:"position" json:"position"`
	ContributorName string      `db:"contributor_name" json:"contributor_name"`
}

type InsertSourceContributorRow struct {
	ContributorID pgtype.UUID        `db:"contributor_id" json:"contributor_id"`
	Name          string             `db:"name" json:"name"`
	Role          string             `db:"role" json:"role"`
	Position      int32              `db:"position" json:"position"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertSourceContributor(ctx context.Context, arg InsertSourceContributorParams) (InsertSourceContributorRow, error) {
	row := q.db.QueryRow(ctx, insertSourceContributor,
		arg.SourceID,
		arg.ContributorID,
		arg.Role,
		arg.Position,
		arg.ContributorName,
	)
	var i InsertSourceContributorRow
	err := row.Scan(
		&i.ContributorID,
		&i.Name,
		&i.Role,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContributorsBySource = `-- name: ListContributorsBySource :many
SELECT c.id, c.name, sc.role, sc.position, c.created_at, c.updated_at
FROM source_contributors sc
JOIN contributors c ON c.id = sc.contributor_id
WHERE sc.source_id = $1
ORDER BY sc.position ASC, c.name ASC
`

type ListContributorsBySourceRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Role      string             `db:"role" json:"role"`
	Position  int32              `db:"position" json:"position"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListContributorsBySource(ctx context.Context, sourceID pgtype.UUID) ([]ListContributorsBySourceRow, error) {
	rows, err := q.db.Query(ctx, listContributorsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContributorsBySourceRow{}
	for rows.Next() {
		var i ListContributorsBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, title, subtitle, type, description, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at
FROM sources
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSourcesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListSources(ctx context.Context, arg ListSourcesParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Type,
			&i.Description,
			&i.Publisher,
			&i.Isbn,
			&i.Doi,
			&i.Url,
			&i.ExternalID,
			&i.Tags,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByType = `-- name: ListSourcesByType :many
SELECT id, title, subtitle, type, description, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at
FROM sources
WHERE type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSourcesByTypeParams struct {
	Type   string `db:"type" json:"type"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListSourcesByType(ctx context.Context, arg ListSourcesByTypeParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Type,
			&i.Description,
			&i.Publisher,
			&i.Isbn,
			&i.Doi,
			&i.Url,
			&i.ExternalID,
			&i.Tags,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSources = `-- name: SearchSources :many
SELECT id, title, subtitle, type, description, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at
FROM sources
WHERE title ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchSourcesParams struct {
	Column1 pgtype.Text `db:"column_1" json:"column_1"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) SearchSources(ctx context.Context, arg SearchSourcesParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, searchSources, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Type,
			&i.Description,
			&i.Publisher,
			&i.Isbn,
			&i.Doi,
			&i.Url,
			&i.ExternalID,
			&i.Tags,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET title = $2, subtitle = $3, type = $4, description = $5, publisher = $6,
    isbn = $7, doi = $8, url = $9, external_id = $10, tags = $11, published_at = $12, updated_at = NOW()
WHERE id = $1
RETURNING id, title, subtitle, type, description, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at
`

type UpdateSourceParams struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Subtitle    pgtype.Text        `db:"subtitle" json:"subtitle"`
	Type        string             `db:"type" json:"type"`
	Description pgtype.Text        `db:"description" json:"description"`
	Publisher   pgtype.Text        `db:"publisher" json:"publisher"`
	Isbn        pgtype.Text        `db:"isbn" json:"isbn"`
	Doi         pgtype.Text        `db:"doi" json:"doi"`
	Url         pgtype.Text        `db:"url" json:"url"`
	ExternalID  pgtype.Text        `db:"external_id" json:"external_id"`
	Tags        []byte             `db:"tags" json:"tags"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.Type,
		arg.Description,
		arg.Publisher,
		arg.Isbn,
		arg.Doi,
		arg.Url,
		arg.ExternalID,
		arg.Tags,
		arg.PublishedAt,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Type,
		&i.Description,
		&i.Publisher,
		&i.Isbn,
		&i.Doi,
		&i.Url,
		&i.ExternalID,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContributor = `-- name: UpsertContributor :one
INSERT INTO contributors (id, name)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertContributorParams struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

func (q *Queries) UpsertContributor(ctx context.Context, arg UpsertContributorParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertContributor, arg.ID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
