// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Bio       pgtype.Text        `json:"bio"`
	BirthDate pgtype.Text        `json:"birth_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Collection struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsPublic    pgtype.Bool        `json:"is_public"`
	SourceIds   []byte             `json:"source_ids"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Note struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Content     string             `json:"content"`
	ContentType string             `json:"content_type"`
	IsPublic    pgtype.Bool        `json:"is_public"`
	Annotations []byte             `json:"annotations"`
	Tags        []byte             `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Outbox struct {
	ID            uuid.UUID          `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       json.RawMessage    `json:"payload"`
	Published     pgtype.Bool        `json:"published"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

type Profile struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	DisplayName   pgtype.Text        `json:"display_name"`
	Bio           pgtype.Text        `json:"bio"`
	PublicProfile pgtype.Bool        `json:"public_profile"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Review struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	SourceID  uuid.UUID          `json:"source_id"`
	Rating    pgtype.Int4        `json:"rating"`
	Content   pgtype.Text        `json:"content"`
	IsPublic  pgtype.Bool        `json:"is_public"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Source struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Subtitle    pgtype.Text        `json:"subtitle"`
	Type        string             `json:"type"`
	Description pgtype.Text        `json:"description"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Publisher   pgtype.Text        `json:"publisher"`
	Isbn        pgtype.Text        `json:"isbn"`
	Doi         pgtype.Text        `json:"doi"`
	Url         pgtype.Text        `json:"url"`
	ExternalID  pgtype.Text        `json:"external_id"`
	Tags        []byte             `json:"tags"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
