// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNotesByUser = `-- name: CountNotesByUser :one
SELECT COUNT(*) FROM notes WHERE user_id = $1
`

func (q *Queries) CountNotesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
    user_id, source_id, content, content_type, is_public, annotations, tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at
`

type CreateNoteParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	SourceID    pgtype.UUID `json:"source_id"`
	Content     string      `json:"content"`
	ContentType string      `json:"content_type"`
	IsPublic    pgtype.Bool `json:"is_public"`
	Annotations []byte      `json:"annotations"`
	Tags        []byte      `json:"tags"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.UserID,
		arg.SourceID,
		arg.Content,
		arg.ContentType,
		arg.IsPublic,
		arg.Annotations,
		arg.Tags,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Content,
		&i.ContentType,
		&i.IsPublic,
		&i.Annotations,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}

const getNote = `-- name: GetNote :one
SELECT id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at FROM notes WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNote(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Content,
		&i.ContentType,
		&i.IsPublic,
		&i.Annotations,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesBySource = `-- name: ListNotesBySource :many
SELECT id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at FROM notes
WHERE source_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotesBySourceParams struct {
	SourceID pgtype.UUID `json:"source_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListNotesBySource(ctx context.Context, arg ListNotesBySourceParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesBySource, arg.SourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Content,
			&i.ContentType,
			&i.IsPublic,
			&i.Annotations,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesByUser = `-- name: ListNotesByUser :many
SELECT id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at FROM notes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotesByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotesByUser(ctx context.Context, arg ListNotesByUserParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Content,
			&i.ContentType,
			&i.IsPublic,
			&i.Annotations,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicNotes = `-- name: ListPublicNotes :many
SELECT id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at FROM notes
WHERE is_public = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicNotesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicNotes(ctx context.Context, arg ListPublicNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listPublicNotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Content,
			&i.ContentType,
			&i.IsPublic,
			&i.Annotations,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET
    content = COALESCE($2, content),
    content_type = COALESCE($3, content_type),
    is_public = COALESCE($4, is_public),
    annotations = COALESCE($5, annotations),
    tags = COALESCE($6, tags),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, source_id, content, content_type, is_public, annotations, tags, created_at, updated_at
`

type UpdateNoteParams struct {
	ID          uuid.UUID   `json:"id"`
	Content     pgtype.Text `json:"content"`
	ContentType pgtype.Text `json:"content_type"`
	IsPublic    pgtype.Bool `json:"is_public"`
	Annotations []byte      `json:"annotations"`
	Tags        []byte      `json:"tags"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.Content,
		arg.ContentType,
		arg.IsPublic,
		arg.Annotations,
		arg.Tags,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Content,
		&i.ContentType,
		&i.IsPublic,
		&i.Annotations,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
