// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSources = `-- name: CountSources :one
SELECT COUNT(*) FROM sources
`

func (q *Queries) CountSources(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (
    title, subtitle, type, description, author_id, publisher,
    isbn, doi, url, external_id, tags, published_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, title, subtitle, type, description, author_id, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at
`

type CreateSourceParams struct {
	Title       string             `json:"title"`
	Subtitle    pgtype.Text        `json:"subtitle"`
	Type        string             `json:"type"`
	Description pgtype.Text        `json:"description"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Publisher   pgtype.Text        `json:"publisher"`
	Isbn        pgtype.Text        `json:"isbn"`
	Doi         pgtype.Text        `json:"doi"`
	Url         pgtype.Text        `json:"url"`
	ExternalID  pgtype.Text        `json:"external_id"`
	Tags        []byte             `json:"tags"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.Title,
		arg.Subtitle,
		arg.Type,
		arg.Description,
		arg.AuthorID,
		arg.Publisher,
		arg.Isbn,
		arg.Doi,
		arg.Url,
		arg.ExternalID,
		arg.Tags,
		arg.PublishedAt,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Type,
		&i.Description,
		&i.AuthorID,
		&i.Publisher,
		&i.Isbn,
		&i.Doi,
		&i.Url,
		&i.ExternalID,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const getSource = `-- name: GetSource :one
SELECT id, title, subtitle, type, description, author_id, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at FROM sources WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSource(ctx context.Context, id uuid.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Type,
		&i.Description,
		&i.AuthorID,
		&i.Publisher,
		&i.Isbn,
		&i.Doi,
		&i.Url,
		&i.ExternalID,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, title, subtitle, type, description, author_id, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at FROM sources
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSourcesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSources(ctx context.Context, arg ListSourcesParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Type,
			&i.Description,
			&i.AuthorID,
			&i.Publisher,
			&i.Isbn,
			&i.Doi,
			&i.Url,
			&i.ExternalID,
			&i.Tags,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByType = `-- name: ListSourcesByType :many
SELECT id, title, subtitle, type, description, author_id, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at FROM sources
WHERE type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSourcesByTypeParams struct {
	Type   string `json:"type"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListSourcesByType(ctx context.Context, arg ListSourcesByTypeParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Type,
			&i.Description,
			&i.AuthorID,
			&i.Publisher,
			&i.Isbn,
			&i.Doi,
			&i.Url,
			&i.ExternalID,
			&i.Tags,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSourcesByTitle = `-- name: SearchSourcesByTitle :many
SELECT id, title, subtitle, type, description, author_id, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at FROM sources
WHERE title ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchSourcesByTitleParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchSourcesByTitle(ctx context.Context, arg SearchSourcesByTitleParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, searchSourcesByTitle, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Type,
			&i.Description,
			&i.AuthorID,
			&i.Publisher,
			&i.Isbn,
			&i.Doi,
			&i.Url,
			&i.ExternalID,
			&i.Tags,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET
    title = COALESCE($2, title),
    subtitle = COALESCE($3, subtitle),
    type = COALESCE($4, type),
    description = COALESCE($5, description),
    author_id = COALESCE($6, author_id),
    publisher = COALESCE($7, publisher),
    isbn = COALESCE($8, isbn),
    doi = COALESCE($9, doi),
    url = COALESCE($10, url),
    external_id = COALESCE($11, external_id),
    tags = COALESCE($12, tags),
    published_at = COALESCE($13, published_at),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, subtitle, type, description, author_id, publisher, isbn, doi, url, external_id, tags, published_at, created_at, updated_at
`

type UpdateSourceParams struct {
	ID          uuid.UUID          `json:"id"`
	Title       pgtype.Text        `json:"title"`
	Subtitle    pgtype.Text        `json:"subtitle"`
	Type        pgtype.Text        `json:"type"`
	Description pgtype.Text        `json:"description"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Publisher   pgtype.Text        `json:"publisher"`
	Isbn        pgtype.Text        `json:"isbn"`
	Doi         pgtype.Text        `json:"doi"`
	Url         pgtype.Text        `json:"url"`
	ExternalID  pgtype.Text        `json:"external_id"`
	Tags        []byte             `json:"tags"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.Type,
		arg.Description,
		arg.AuthorID,
		arg.Publisher,
		arg.Isbn,
		arg.Doi,
		arg.Url,
		arg.ExternalID,
		arg.Tags,
		arg.PublishedAt,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Type,
		&i.Description,
		&i.AuthorID,
		&i.Publisher,
		&i.Isbn,
		&i.Doi,
		&i.Url,
		&i.ExternalID,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
